name: Build Workflow

on:
  push:
#    branches: master

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyInstaller
      - name: Run PyInstaller
        run: |
          python -m PyInstaller epson_print_conf.spec -- --default

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/epson_print_conf.exe
