name: Mark stale issues and automatically close them

on:
  schedule:
  - cron: '00 23 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v9  # https://github.com/actions/stale
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue becomed stale because of no feedback for 15 days. Remove the stale label or add a comment; otherwise, this will be automatically closed in 30 days.'
        stale-pr-message: 'This PR becomed stale because of no feedback for 30 days.'
        days-before-stale: 15
        days-before-close: 30
        close-issue-message: 'This issue was closed because it has been stalled for 30 days with no activity.'
        days-before-pr-close: -1
        any-of-labels: answered,needs-rebase,inactive,Awaiting-Response,question,invalid,duplicate,wontfix,comment
        exempt-all-pr-assignees: true
